name: Terraform

on:
  push:
    branches:
      - main
      - 'devel'
      - 'stage'
      - 'prod'
  pull_request:
    branches:
      - 'devel'
      - 'stage'
      - 'prod'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform-build-devel:
    runs-on: ubuntu-latest
    environment: devel
    if: github.ref == 'refs/heads/devel'
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.2"
      - run: terraform init
        name: terraform init
        working-directory: "devel"
      - run: terraform plan
        name: terraform plan
        working-directory: "devel"
      - run: terraform apply --auto-approve
        name: terraform apply
        working-directory: "devel"
  terraform-build-stage:
    runs-on: ubuntu-latest
    environment: stage
    if: github.ref == 'refs/heads/stage'
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.5.2"
      - run: terraform init
        name: terraform init
        working-directory: "stage"
      - run: terraform plan
        name: terraform plan
        working-directory: "stage"
      - run: terraform apply --auto-approve
        name: terraform apply
        working-directory: "stage"
  terraform-build-prod:
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.5.2"
      - run: terraform init
        name: terraform init
        working-directory: "prod"
      - run: terraform plan
        name: terraform plan
        working-directory: "prod"
      - run: terraform apply --auto-approve
        name: terraform apply
        working-directory: "prod"